Repository AdaCore/e3-core, pull requests merged in 2024-02, with the labels that each got.

#676 Fix pre-release version management
  src/e3/python/pypi.py
Labels: bug

#675 Sort elements in SPDX document
  src/e3/spdx.py
  tests/tests_e3/spdx_test.py
Labels: enhancement

#679 Add JsonData class to json module
  src/e3/json.py
  tests/tests_e3/json_test.py
Labels: enhancement, testsuite

#681 Implementation of VEX specifications version 1.0.0
  src/e3/encoding/__init__.py
  src/e3/encoding/vex.py
  src/e3/spdx.py
  src/e3/sys.py
  tests/tests_e3/encoding/__init__.py
  tests/tests_e3/encoding/vex_test.py
Labels: enhancement
